---
title: "Transport Planning Method Assignment 2"
author: "Wanying Sun(2516202S)"
date: "04/03/2021"
output:
pdf_document: default
---



**(word count: xxxx words, excluding literatures)**
<br />
<br />

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = 'center', out.width = '80%', echo = TRUE)
```

```{r data, include = FALSE}
library(tidyverse)
library(dplyr)
library(car)
library(erer)
library(vcd)
library(Hmisc)
library(pscl)
library(ggcorrplot)
library(ggplot2)
library(corrplot)
library(kableExtra)
library(devtools)
library(broom)
```

```{r hhsurvey person}
hhsurvey_person <- read.csv("/Volumes/Ying/Salmon/UofG/Semester2/TPM/Assignment2/data/2017-2019-pr2-datafiles/2017-2019-pr2-2-Person.csv", header = TRUE)
hhsurvey_person <- hhsurvey_person %>%
  dplyr::select(hhid, survey_year, gender, age, education, license, smartphone_type, smartphone_age, 
employment, commute_mode, av_interest_1, av_interest_2, av_concern_1, av_concern_2, av_concern_3, av_concern_4, av_concern_5) %>% drop_na()

dim(hhsurvey_person)

```

```{r}
hhsurvey_person <- read.csv("/Volumes/Ying/Salmon/UofG/Semester2/TPM/Assignment2/data/2017-2019-pr2-datafiles/2017-2019-pr2-2-Person.csv", header = TRUE)
hhsurvey_person <- hhsurvey_person %>%
  dplyr::select(hhid, survey_year, gender, age, education, license, smartphone_type, employment, commute_mode, workpass, av_interest_1, av_interest_2, av_concern_1, av_concern_2, av_concern_3, av_concern_4, av_concern_5) %>%
  drop_na()
hhsurvey_person <- hhsurvey_person %>% filter(survey_year == '2019')
hhsurvey_person $ survey_year <- NULL
str(hhsurvey_person)

# Household filter
hhsurvey_household <- read.csv("/Volumes/Ying/Salmon/UofG/Semester2/TPM/Assignment2/data/2017-2019-pr2-datafiles/2017-2019-pr2-1-Household.csv", header = TRUE)
hhsurvey_household <- hhsurvey_household %>% 
  dplyr::select(hhid, survey_year, numchildren, vehicle_count, hhincome_broad, cityofseattle) %>% 
  drop_na()
hhsurvey_household <- hhsurvey_household %>% filter(survey_year == '2019')
hhsurvey_household $ survey_year<- NULL
str(hhsurvey_household)

# Vehicle filter
hhsurvey_vehicle <- read.csv('/Volumes/Ying/Salmon/UofG/Semester2/TPM/Assignment2/data/2017-2019-pr2-datafiles/2017-2019-pr2-3-Vehicle.csv', header = TRUE)
hhsurvey_vehicle <- hhsurvey_vehicle %>% 
  dplyr::select(hhid, survey_year, disability) %>%
  drop_na()
hhsurvey_vehicle <- hhsurvey_vehicle %>% filter(survey_year == '2019')
hhsurvey_vehicle $ survey_year <- NULL
str(hhsurvey_vehicle)

# Trip filter
hhsurvey_trip <- read.csv('/Volumes/Ying/Salmon/UofG/Semester2/TPM/Assignment2/data/2017-2019-pr2-datafiles/2017-2019-pr2-5-Trip.csv', header = TRUE)
hhsurvey_trip <- hhsurvey_trip %>% 
  dplyr::select(hhid, o_purp_cat, survey_year) %>% 
  drop_na()
hhsurvey_trip <- hhsurvey_trip %>% filter(survey_year == '2019')
hhsurvey_trip $ survey_year <- NULL
str(hhsurvey_trip)

# total dataset:
hhsurvey_m1 <- merge(hhsurvey_person, hhsurvey_household, by = 'hhid')
hhsurvey_m2 <- merge(hhsurvey_m1, hhsurvey_vehicle, by = 'hhid')
hhsurvey_m3 <- merge(hhsurvey_m2, hhsurvey_trip, by = 'hhid')
hhsurvey_merge <- hhsurvey_m3
str(hhsurvey_merge)
```

```{r hhsurvey person combined}
# filter gender
hhsurvey_person1 <- hhsurvey_person %>%
  filter(gender == 'Female')
hhsurvey_person2 <- hhsurvey_person %>%
  filter(gender == 'Male')
hhsurvey_person <- rbind(hhsurvey_person1, hhsurvey_person2)
dim(hhsurvey_person)

# filter age
hhsurvey_person3 <- hhsurvey_person %>%
  filter(age == '18-24 years')
hhsurvey_person4 <- hhsurvey_person %>%
  filter(age == '25-34 years')
hhsurvey_person5 <- hhsurvey_person %>%
  filter(age == '35-44 years')
hhsurvey_person6 <- hhsurvey_person %>%
  filter(age == '45-54 years')
hhsurvey_person7 <- hhsurvey_person %>%
  filter(age == '55-64 years')
hhsurvey_person <- rbind(hhsurvey_person3, hhsurvey_person4, hhsurvey_person5, hhsurvey_person6, hhsurvey_person7)
dim(hhsurvey_person)

# filter education
## without an education degree
hhsurvey_person8 <- hhsurvey_person %>%
  filter(education == 'Less than high school')
hhsurvey_person9 <- hhsurvey_person %>%
  filter(education == 'High school graduate')
hhsurvey_person10 <- hhsurvey_person %>%
  filter(education == 'Some college')
hhsurvey_person11 <- hhsurvey_person %>%
  filter(education == 'Vocational/technical training')


##with a degree
hhsurvey_person12 <- hhsurvey_person %>%
  filter(education == 'Associates degree')
hhsurvey_person13 <- hhsurvey_person %>%
  filter(education == 'Bachelor degree')
hhsurvey_person14 <- hhsurvey_person %>%
  filter(education == 'Graduate/post-graduate degree')
hhsurvey_person <- rbind(hhsurvey_person8, hhsurvey_person9, hhsurvey_person10, hhsurvey_person11, hhsurvey_person12, hhsurvey_person13, hhsurvey_person14)
dim(hhsurvey_person)

#filter employment
hhsurvey_person15 <- hhsurvey_person %>%
  filter(employment == 'Self-employed')
hhsurvey_person16 <- hhsurvey_person %>%
  filter(employment == 'Employed part time (fewer than 35 hours/week, paid)')
hhsurvey_person17 <- hhsurvey_person %>%
  filter(employment == 'Employed full time (35+ hours/week, paid)')
hhsurvey_person <- rbind(hhsurvey_person15, hhsurvey_person16, hhsurvey_person17)
dim(hhsurvey_person)

##have a license
hhs1 <- hhsurvey_person %>%
  filter(license == 'Yes, has an intermediate or unrestricted license')
hhs2 <- hhsurvey_person %>%
  filter(license == 'Yes, has a learner’s permit')
##do not have a license
hhs3 <- hhsurvey_person %>%
  filter(license == 'No, does not have a license or permit')
hhsurvey_person <- rbind(hhs1, hhs2, hhs3)
dim(hhsurvey_person)

#filter smartphone type
hhsurvey_person20 <- hhsurvey_person %>%
  filter(smartphone_type == 'Yes, has an Android phone')
hhsurvey_person21 <- hhsurvey_person %>%
  filter(smartphone_type == 'Yes, has an Apple iPhone')
hhsurvey_person22 <- hhsurvey_person %>%
  filter(smartphone_type == 'Yes, has a Windows phone')
hhsurvey_person23 <- hhsurvey_person %>%
  filter(smartphone_type == 'Yes, has a blackberry')
hhsurvey_person24 <- hhsurvey_person %>%
  filter(smartphone_type == 'Yes, has other type of smartphone')

#do not have a phone
hhsurvey_person25 <- hhsurvey_person %>%
  filter(smartphone_type == 'No, does not have a smartphone')
hhsurvey_person <- rbind(hhsurvey_person20, hhsurvey_person21, hhsurvey_person22, hhsurvey_person23, hhsurvey_person24, hhsurvey_person25)
dim(hhsurvey_person)

# filter commute mode
#public transport
hhsurvey_person26 <- hhsurvey_person %>%
  filter(commute_mode == 'Bus (public transit)')
hhsurvey_person27 <- hhsurvey_person %>%
  filter(commute_mode == 'Commuter rail (Sounder, Amtrak)')
hhsurvey_person28 <- hhsurvey_person %>%
  filter(commute_mode == 'Urban rail (Link light rail, monorail)')
hhsurvey_person29 <- hhsurvey_person %>%
  filter(commute_mode == 'Streetcar')
hhsurvey_person30 <- hhsurvey_person %>%
  filter(commute_mode == 'Paratransit')
hhsurvey_person31 <- hhsurvey_person %>%
  filter(commute_mode == 'Taxi (e.g., Yellow Cab)')
hhsurvey_person32 <- hhsurvey_person %>%
  filter(commute_mode == 'Vanpool')
hhsurvey_person33 <- hhsurvey_person %>%
  filter(commute_mode == 'Ferry or water taxi')
hhsurvey_person34 <- hhsurvey_person %>%
  filter(commute_mode == 'Carpool ONLY with other household members')
hhsurvey_person35 <- hhsurvey_person %>%
  filter(commute_mode == 'Carpool with other people not in household (may also include household members)')
hhsurvey_person36 <- hhsurvey_person %>%
  filter(commute_mode == 'Other hired service (Uber, Lyft, or other smartphone-app car service')

#driving car
hhsurvey_person37 <- hhsurvey_person %>%
  filter(commute_mode == 'Drive alone')

#active travel
hhsurvey_person38 <- hhsurvey_person %>%
  filter(commute_mode == 'Walk, jog, or wheelchair')
hhsurvey_person39 <- hhsurvey_person %>%
  filter(commute_mode == 'Bicycle or e-bike')
hhsurvey_person40 <- hhsurvey_person %>%
  filter(commute_mode == 'Motorcycle/moped')
hhsurvey_person <- rbind(hhsurvey_person26, hhsurvey_person27, hhsurvey_person28, hhsurvey_person29, hhsurvey_person30, hhsurvey_person31, hhsurvey_person32, hhsurvey_person33, hhsurvey_person34, hhsurvey_person35, hhsurvey_person36, hhsurvey_person37, hhsurvey_person38, hhsurvey_person39, hhsurvey_person40)
dim(hhsurvey_person)

#perceived trust
##av_concern_1
hhsurvey_person42 <- hhsurvey_person %>%
  filter(av_concern_1 == 'Very concerned')
hhsurvey_person43 <- hhsurvey_person %>%
  filter(av_concern_1 == 'Somewhat concerned')
hhsurvey_person44 <- hhsurvey_person %>%
  filter(av_concern_1 == 'Somewhat unconcerned')
hhsurvey_person45 <- hhsurvey_person %>%
  filter(av_concern_1 == 'Not at all concerned')
hhsurvey_person46 <- hhsurvey_person %>%
  filter(av_concern_1 == 'Neutral')
hhsurvey_person <- rbind(hhsurvey_person42, hhsurvey_person43, hhsurvey_person44, hhsurvey_person45, hhsurvey_person46)
dim(hhsurvey_person)
##av_concern_2
hhsurvey_person47 <- hhsurvey_person %>%
  filter(av_concern_2 == 'Very concerned')
hhsurvey_person48 <- hhsurvey_person %>%
  filter(av_concern_2 == 'Somewhat concerned')
hhsurvey_person49 <- hhsurvey_person %>%
  filter(av_concern_2 == 'Somewhat unconcerned')
hhsurvey_person50 <- hhsurvey_person %>%
  filter(av_concern_2 == 'Not at all concerned')
hhsurvey_person51 <- hhsurvey_person %>%
  filter(av_concern_2 == 'Neutral')

hhsurvey_person <- rbind(hhsurvey_person47, hhsurvey_person48, hhsurvey_person49, hhsurvey_person50, hhsurvey_person51)
dim(hhsurvey_person)

##av_concern_3
hhsurvey_person52 <- hhsurvey_person %>%
  filter(av_concern_3 == 'Very concerned')
hhsurvey_person53 <- hhsurvey_person %>%
  filter(av_concern_3 == 'Somewhat concerned')
hhsurvey_person54 <- hhsurvey_person %>%
  filter(av_concern_3 == 'Somewhat unconcerned')
hhsurvey_person55 <- hhsurvey_person %>%
  filter(av_concern_3 == 'Not at all concerned')
hhsurvey_person56 <- hhsurvey_person %>%
  filter(av_concern_3 == 'Neutral')
hhsurvey_person <- rbind(hhsurvey_person52, hhsurvey_person53, hhsurvey_person54, hhsurvey_person55, hhsurvey_person56)
dim(hhsurvey_person)

#av_concern_4
hhsurvey_person57 <- hhsurvey_person %>%
  filter(av_concern_4 == 'Very concerned')
hhsurvey_person58 <- hhsurvey_person %>%
  filter(av_concern_4 == 'Somewhat concerned')
hhsurvey_person59 <- hhsurvey_person %>%
  filter(av_concern_4 == 'Somewhat unconcerned')
hhsurvey_person60 <- hhsurvey_person %>%
  filter(av_concern_4 == 'Not at all concerned')
hhsurvey_person61 <- hhsurvey_person %>%
  filter(av_concern_4 == 'Neutral')
hhsurvey_person <- rbind(hhsurvey_person57, hhsurvey_person58, hhsurvey_person59, hhsurvey_person60, hhsurvey_person61)
dim(hhsurvey_person)

#av_concern_5
hhsurvey_person62 <- hhsurvey_person %>%
  filter(av_concern_5 == 'Very concerned')
hhsurvey_person63 <- hhsurvey_person %>%
  filter(av_concern_5 == 'Somewhat concerned')
hhsurvey_person64 <- hhsurvey_person %>%
  filter(av_concern_5 == 'Somewhat unconcerned')
hhsurvey_person65 <- hhsurvey_person %>%
  filter(av_concern_5 == 'Not at all concerned')
hhsurvey_person66 <- hhsurvey_person %>%
  filter(av_concern_5 == 'Neutral')
hhsurvey_person <- rbind(hhsurvey_person62, hhsurvey_person63, hhsurvey_person64, hhsurvey_person65, hhsurvey_person66)
dim(hhsurvey_person)


```

```{r av_interest independent variable!!!!}
#fully
##av_interest_1
hhsurvey_person67 <- hhsurvey_person %>%
  filter(av_interest_1 == 'Very interested')
hhsurvey_person68 <- hhsurvey_person %>%
  filter(av_interest_1 == 'Somewhat interested')
hhsurvey_person69 <- hhsurvey_person %>%
  filter(av_interest_1 == 'Somewhat uninterested')
hhsurvey_person70 <- hhsurvey_person %>%
  filter(av_interest_1 == 'Not at all interested')
hhsurvey_person71 <- hhsurvey_person %>%
  filter(av_interest_1 == 'Neutral')
hhsurvey_person <- rbind(hhsurvey_person67, hhsurvey_person68, hhsurvey_person69, hhsurvey_person70, hhsurvey_person71)
dim(hhsurvey_person)

#partial
##av_interest_2
hhsurvey_person72 <- hhsurvey_person %>%
  filter(av_interest_2 == 'Very interested')
hhsurvey_person73 <- hhsurvey_person %>%
  filter(av_interest_2 == 'Somewhat interested')
hhsurvey_person74 <- hhsurvey_person %>%
  filter(av_interest_2 == 'Somewhat uninterested')
hhsurvey_person75 <- hhsurvey_person %>%
  filter(av_interest_2 == 'Not at all interested')
hhsurvey_person76 <- hhsurvey_person %>%
  filter(av_interest_2 == 'Neutral')
hhsurvey_person <- rbind(hhsurvey_person72, hhsurvey_person73, hhsurvey_person74, hhsurvey_person75, hhsurvey_person76)
dim(hhsurvey_person)

```

```{r hhsurvey person smartphone age not in 2019}
#把2017年的数据放进来作为2019年的数据
# filter smartphone age
hhsurvey_person18 <- hhsurvey_person %>% 
  filter(smartphone_age == "No")
hhsurvey_person19 <- hhsurvey_person %>% 
  filter(smartphone_age == "Yes")
hhsurvey_person <- rbind(hhsurvey_person18, hhsurvey_person19)
dim(hhsurvey_person)
```

```{r hhsurvey household}
hhsurvey_household <- read.csv("/Volumes/SALMON/Salmon/UofG/Dissertation/data/2017-2019-pr2-datafiles/2017-2019-pr2-1-Household.csv", header = TRUE)
# Household filter
hhsurvey_household <- hhsurvey_household %>% 
  dplyr::select(hhid, survey_year, vehicle_count, hhincome_broad, cityofseattle, numchildren) %>%
  drop_na()
dim(hhsurvey_household)
```

```{r hhsurvey household combined}
# filter income 
hhsurvey_income1 <- hhsurvey_household %>%
  filter(hhincome_broad == 'Under $25,000')
hhsurvey_income2 <- hhsurvey_household %>%
  filter(hhincome_broad == '$25,000-$49,999')
hhsurvey_income3 <- hhsurvey_household %>%
  filter(hhincome_broad == '$50,000-$74,999')
hhsurvey_income4 <- hhsurvey_household %>%
  filter(hhincome_broad == '$75,000-$99,999')
hhsurvey_income5 <- hhsurvey_household %>%
  filter(hhincome_broad == '$100,000 or more')

hhsurvey_household <- rbind(hhsurvey_income1, hhsurvey_income2, hhsurvey_income3, hhsurvey_income4, hhsurvey_income5)
dim(hhsurvey_household)

# filter vehicle number
hv0 <- hhsurvey_household %>%
  filter(vehicle_count == '0 (no vehicles)')
hv1 <- hhsurvey_household %>%
  filter(vehicle_count == '1')
hv2 <- hhsurvey_household %>%
  filter(vehicle_count == '2')
hv3 <- hhsurvey_household %>%
  filter(vehicle_count == '3')
hv4 <- hhsurvey_household %>%
  filter(vehicle_count == '4')
hv5 <- hhsurvey_household %>%
  filter(vehicle_count == '5')
hv6 <- hhsurvey_household %>%
  filter(vehicle_count == '6')
hv7 <- hhsurvey_household %>%
  filter(vehicle_count == '7')
hv8 <- hhsurvey_household %>%
  filter(vehicle_count == '8')
hv9 <- hhsurvey_household %>%
  filter(vehicle_count == '9')
hv10 <- hhsurvey_household %>%
  filter(vehicle_count == '10 or more vehicles')
hhsurvey_vehicle <- rbind(hv0, hv1, hv2, hv3, hv4, hv5, hv6, hv7, hv8, hv9, hv10)
dim(hhsurvey_vehicle)

hv11 <- hhsurvey_household %>%
  filter(cityofseattle == 'Yes')
hv12 <- hhsurvey_household %>%
  filter(cityofseattle == 'No')
hhsurvey_household <- rbind(hv11, hv12)
dim(hhsurvey_household)

hv13 <- hhsurvey_household %>%
  filter(numchildren == '1')
hv14 <- hhsurvey_household %>%
  filter(numchildren == '2')
hv15 <- hhsurvey_household %>%
  filter(numchildren == '3')
hv16 <- hhsurvey_household %>%
  filter(numchildren == '4')
hv17 <- hhsurvey_household %>%
  filter(numchildren == '5')
hv18 <- hhsurvey_household %>%
  filter(numchildren == '6')
hv19 <- hhsurvey_household %>%
  filter(numchildren == '0')
hhsurvey_household <- rbind(hv13, hv14, hv15, hv16, hv17, hv18, hv19)
dim(hhsurvey_household)
hhsurvey_m1 <- merge(hhsurvey_person, hhsurvey_household, by = 'hhid')
dim(hhsurvey_m1)
```

```{r hhsurvey vehicle}
hhsurvey_vehicle <- read.csv('/Volumes/SALMON/Salmon/UofG/Dissertation/data/2017-2019-pr2-datafiles/2017-2019-pr2-3-Vehicle.csv', header = TRUE)

hhsurvey_vehicle <- hhsurvey_vehicle %>% 
  dplyr::select(hhid, survey_year, disability) %>%
  drop_na()
dim(hhsurvey_vehicle)
```

```{r hhsurvey vehicle combined}

hhe1 <- hhsurvey_vehicle %>%
  filter(disability == 'Yes')
hhe2 <- hhsurvey_vehicle %>%
  filter(disability == 'No')
hhsurvey_vehicle <- rbind(hhe1, hhe2)
dim(hhsurvey_trip)
hhsurvey_m2 <- merge(hhsurvey_m1, hhsurvey_vehicle, by = 'hhid')
dim(hhsurvey_m2)
```

```{r hhsurvey trip}
hhsurvey_trip <- read.csv('/Volumes/SALMON/Salmon/UofG/Dissertation/data/2017-2019-pr2-datafiles/2017-2019-pr2-5-Trip.csv', header = TRUE)

hhsurvey_trip <- hhsurvey_trip %>% 
  dplyr::select(hhid, o_purp_cat, survey_year) %>% 
  drop_na()
dim(hhsurvey_trip)
```

```{r hhsurvey trip combined}
hht2 <- hhsurvey_trip %>%
  filter(o_purp_cat == 'Work')
hht3 <- hhsurvey_trip %>%
  filter(o_purp_cat == 'Work-related')
hhsurvey_trip <- rbind(hht2, hht3) 
dim(hhsurvey_trip)
hhsurvey_m3 <- merge(hhsurvey_person, hhsurvey_trip, by = 'hhid')
dim(hhsurvey_m3)
```

```{r re-categorise the values of each variables}
#gender
hhsurvey_merge $ gender[hhsurvey_merge $ gender == 'Male'] <- 1
hhsurvey_merge $ gender[hhsurvey_merge $ gender == 'Female'] <- 2
length(unique(hhsurvey_merge $ gender))

#age
hhsurvey_merge $ age[hhsurvey_merge $ age == '18-24 years'] <- 1
hhsurvey_merge $ age[hhsurvey_merge $ age == '25-34 years'] <- 2
hhsurvey_merge $ age[hhsurvey_merge $ age == '35-44 years'] <- 3
hhsurvey_merge $ age[hhsurvey_merge $ age == '45-54 years'] <- 4
hhsurvey_merge $ age[hhsurvey_merge $ age == '55-64 years'] <- 5
length(unique(hhsurvey_merge $ age))

#education
## without a degree
hhsurvey_merge $ education[hhsurvey_merge $ education == 'Less than high school'] <- 'Without a higher education degree'
hhsurvey_merge $ education[hhsurvey_merge $ education == 'High school graduate'] <-'Without a higher education degree'
hhsurvey_merge $ education[hhsurvey_merge $ education == 'Some college'] <- 'Without a higher education degree'
hhsurvey_merge $ education[hhsurvey_merge $ education == 'Vocational/technical training'] <- 'Without a higher education degree'

## with a degree
hhsurvey_merge $ education[hhsurvey_merge $ education == 'Associates degree'] <- 'With a higher education degree'
hhsurvey_merge $ education[hhsurvey_merge $ education == 'Bachelor degree'] <- 'With a higher education degree'
hhsurvey_merge $ education[hhsurvey_merge $ education == 'Graduate/post-graduate degree'] <- 'With a higher education degree'
length(unique(hhsurvey_merge $ education))
#describe(hhsurvey_merge $ education)


#license
##have a license
hhsurvey_merge $ license[hhsurvey_merge $ license == 'Yes, has an intermediate or unrestricted license'] <- 'have a license'
hhsurvey_merge $ license[hhsurvey_merge $ license == 'Yes, has a learner’s permit'] <- 'have a license'
##do not have a license
hhsurvey_merge $ license[hhsurvey_merge $ license == 'No, does not have a license or permit'] <- 'do not have a license'
length(unique(hhsurvey_merge $ license))
#describe(hhsurvey_merge $ license)


#use a phone more than 4 years?
hhsurvey_merge $ smartphone_age[hhsurvey_merge $ smartphone_age == 'Yes'] <- 1
hhsurvey_merge $ smartphone_age[hhsurvey_merge $ smartphone_age == 'No'] <- 2
length(unique(hhsurvey_merge $ smartphone_age))
describe(hhsurvey_merge $ smartphone_age)



#living in the urban area
hhsurvey_merge $ cityofseattle[hhsurvey_merge $ cityofseattle == 'Yes'] <- 1
hhsurvey_merge $ cityofseattle[hhsurvey_merge $ cityofseattle == 'No'] <- 2
length(unique(hhsurvey_merge $ cityofseattle))
#describe(hhsurvey_merge $ cityofseattle)

#income
hhsurvey_merge $ hhincome_broad[hhsurvey_merge $ hhincome_broad == 'Under $25,000'] <- 'lower than $25,000'
hhsurvey_merge $ hhincome_broad[hhsurvey_merge $ hhincome_broad == '$25,000-$49,999'] <- '$25,000-$49,999'
hhsurvey_merge $ hhincome_broad[hhsurvey_merge $ hhincome_broad == '$50,000-$74,999'] <- '$50,000-$74,999'
hhsurvey_merge $ hhincome_broad[hhsurvey_merge $ hhincome_broad == '$75,000-$99,999'] <- '$75,000-$99,999'
hhsurvey_merge $ hhincome_broad[hhsurvey_merge $ hhincome_broad == '$100,000 or more'] <- '$100,000 or more'

length(unique(hhsurvey_merge $ hhincome_broad))
#describe(hhsurvey_merge $ hhincome_broad)

#commute mode
## public transport
hhsurvey_merge $ commute_mode[hhsurvey_merge $ commute_mode == 'Bus (public transit)'] <- 'public transport users'
hhsurvey_merge $ commute_mode[hhsurvey_merge $ commute_mode == 'Commuter rail (Sounder, Amtrak)'] <- 'public transport users'
hhsurvey_merge $ commute_mode[hhsurvey_merge $ commute_mode == 'Urban rail (Link light rail, monorail)'] <- 'public transport users'
hhsurvey_merge $ commute_mode[hhsurvey_merge $ commute_mode == 'Streetcar'] <- 'public transport users'
hhsurvey_merge $ commute_mode[hhsurvey_merge $ commute_mode == 'Paratransit'] <- 'public transport users'
hhsurvey_merge $ commute_mode[hhsurvey_merge $ commute_mode == 'Ferry or water taxi'] <- 'public transport users' 
hhsurvey_merge $ commute_mode[hhsurvey_merge $ commute_mode == 'Taxi (e.g., Yellow Cab)'] <- 'public transport users' 
hhsurvey_merge $ commute_mode[hhsurvey_merge $ commute_mode == 'Carpool ONLY with other household members'] <- 'public transport users'
hhsurvey_merge $ commute_mode[hhsurvey_merge $ commute_mode == 'Carpool with other people not in household (may also include household members)'] <- 'public transport users' 
hhsurvey_merge $ commute_mode[hhsurvey_merge $ commute_mode == 'Other hired service (Uber, Lyft, or other smartphone-app car service'] <- 'public transport users'
hhsurvey_merge $ commute_mode[hhsurvey_merge $ commute_mode == 'Vanpool'] <- 'public transport users'

##driving car users
hhsurvey_merge $ commute_mode[hhsurvey_merge $ commute_mode == 'Drive alone'] <- 'driving car users' 
length(unique(hhsurvey_merge $ commute_mode))
#describe(hhsurvey_merge $ commute_mode)

# buy an AV
## dont buy
hhsurvey_merge $ av_interest_6[hhsurvey_merge $ av_interest_6 == 'Not at all interested'] <- 'do not want to buy an AV'
hhsurvey_merge $ av_interest_6[hhsurvey_merge $ av_interest_6 == 'Somewhat uninterested'] <- 'do not want to buy an AV'

##want to buy
hhsurvey_merge $ av_interest_6[hhsurvey_merge $ av_interest_6 == 'Very interested'] <- 'want to buy an AV'
hhsurvey_merge $ av_interest_6[hhsurvey_merge $ av_interest_6 == 'Somewhat interested'] <- 'want to buy an AV'
length(unique(hhsurvey_merge $ av_interest_6))
#describe(hhsurvey_merge $ av_interest_6)
hhsurvey_merge

summary(hhsurvey_merge)

```

```{r assign values for each re-catagorised values}
#gender
hhsurvey_merge $ gender[hhsurvey_merge $ gender == 'Male'] <- 1
hhsurvey_merge $ gender[hhsurvey_merge $ gender == 'Female'] <- 2
length(unique(hhsurvey_merge $ gender))
#describe(hhsurvey_merge $ gender)


#age
hhsurvey_merge $ age[hhsurvey_merge $ age == '18-24 years'] <- 1
hhsurvey_merge $ age[hhsurvey_merge $ age == '25-34 years'] <- 2
hhsurvey_merge $ age[hhsurvey_merge $ age == '35-44 years'] <- 3
hhsurvey_merge $ age[hhsurvey_merge $ age == '45-54 years'] <- 4
hhsurvey_merge $ age[hhsurvey_merge $ age == '55-64 years'] <- 5
length(unique(hhsurvey_merge $ age))
#describe(hhsurvey_merge $ age)

#employment
hhsurvey_merge $ employment[hhsurvey_merge $ employment == 'Employed full time (35+ hours/week, paid)'] <- 1
hhsurvey_merge $ employment[hhsurvey_merge $ employment == 'Employed part time (fewer than 35 hours/week, paid)'] <- 2
hhsurvey_merge $ employment[hhsurvey_merge $ employment == 'Self-employed'] <- 3
length(unique(hhsurvey_merge $ employment))
#describe(hhsurvey_merge $ employment)


#education
hhsurvey_merge $ education[hhsurvey_merge $ education == 'With a higher education degree'] <- 1
hhsurvey_merge $ education[hhsurvey_merge $ education == 'Without a higher education degree'] <- 2
length(unique(hhsurvey_merge $ education))
#describe(hhsurvey_merge $ education)


#license
hhsurvey_merge $ license[hhsurvey_merge $ license == 'have a license'] <- 1
hhsurvey_merge $ license[hhsurvey_merge $ license == 'do not have a license'] <- 2
length(unique(hhsurvey_merge $ license))
#describe(hhsurvey_merge $ license)


#use a phone more than 4 years?
hhsurvey_merge $ smartphone_age[hhsurvey_merge $ smartphone_age == 'Yes'] <- 1
hhsurvey_merge $ smartphone_age[hhsurvey_merge $ smartphone_age == 'No'] <- 2
length(unique(hhsurvey_merge $ smartphone_age))
#describe(hhsurvey_merge $ smartphone_age)



#living in the urban area
hhsurvey_merge $ cityofseattle[hhsurvey_merge $ cityofseattle == 'Yes'] <- 1
hhsurvey_merge $ cityofseattle[hhsurvey_merge $ cityofseattle == 'No'] <- 2
length(unique(hhsurvey_merge $ cityofseattle))
#describe(hhsurvey_merge $ cityofseattle)

#income
hhsurvey_merge $ hhincome_broad[hhsurvey_merge $ hhincome_broad == 'lower than $25,000'] <- 1
hhsurvey_merge $ hhincome_broad[hhsurvey_merge $ hhincome_broad == '$25,000-$49,999'] <- 2
hhsurvey_merge $ hhincome_broad[hhsurvey_merge $ hhincome_broad == '$50,000-$74,999'] <- 3
hhsurvey_merge $ hhincome_broad[hhsurvey_merge $ hhincome_broad == '$75,000-$99,999'] <- 4
hhsurvey_merge $ hhincome_broad[hhsurvey_merge $ hhincome_broad == '$100,000 or more'] <- 5
length(unique(hhsurvey_merge $ hhincome_broad))
#describe(hhsurvey_merge $ hhincome_broad)

#commute mode
## public transport
hhsurvey_merge $ commute_mode[hhsurvey_merge $ commute_mode == 'public transport users'] <- 0
hhsurvey_merge $ commute_mode[hhsurvey_merge $ commute_mode == 'driving car users'] <- 1
length(unique(hhsurvey_merge $ commute_mode))
#describe(hhsurvey_merge $ commute_mode)

# buy an AV
hhsurvey_merge $ av_interest_6[hhsurvey_merge $ av_interest_6 == 'do not want to buy an AV'] <- 0
hhsurvey_merge $ av_interest_6[hhsurvey_merge $ av_interest_6 == 'want to buy an AV'] <- 1
length(unique(hhsurvey_merge $ av_interest_6))
#describe(hhsurvey_merge $ av_interest_6)

hhsurvey_merge
dim(hhsurvey_merge)

```

```{r}
car_av <- count(hhsurvey_merge %>% dplyr::select(av_interest_6, commute_mode) %>% filter(av_interest_6 == '1', commute_mode == '1'))
car_noav <- count(hhsurvey_merge %>% dplyr::select(av_interest_6, commute_mode) %>% filter(av_interest_6 == '0', commute_mode == '1'))
pub_av <- count(hhsurvey_merge %>% dplyr::select(av_interest_6, commute_mode) %>% filter(av_interest_6 == '1', commute_mode == '0'))
pub_noav <- count(hhsurvey_merge %>% dplyr::select(av_interest_6, commute_mode) %>% filter(av_interest_6 == '0', commute_mode == '0'))

row1 <- rbind(car_av, pub_av)
row2 <- rbind(car_noav, pub_noav)
row1
row2
newrow <- cbind(row1, row2)
newrow


colnames(newrow) <- c("want to buy an AV", "do not want to buy an AV")
rownames(newrow) <- c('car users', 'public transport users')
kbl(newrow,
    align = "c") %>%
   kable_styling(bootstrap_options = "striped",
                 font_size = 15) %>%
    kable_classic(full_width = F, html_font = "Calibri")

ggplot(newrow, aes(x = , y = Percentage)) + 
  ggtitle("Percentage and number of people voted Yes and No") +
  labs(y = "", 
       x = "Vote Results, 2 Oct 2009") +
  theme(plot.title = element_text(size = 15, hjust = 0.5), 
        plot.caption = element_text(size = 10, hjust = 0.5), 
        axis.text.x = element_text(face = "bold", size = 8), 
        axis.text.y = element_text(face = "bold", size = 8)) +
  geom_col() + 
  geom_label(aes(label = freq), vjust = 1.2)
```

```{r 3 convert into factor}
#convert into factor
hhsurvey_merge $ gender <- as.factor(hhsurvey_merge $ gender)
hhsurvey_merge $ age <- as.factor(hhsurvey_merge $ age)
hhsurvey_merge $ education <- as.factor(hhsurvey_merge $ education)
hhsurvey_merge $ license <- as.factor(hhsurvey_merge $ license)
hhsurvey_merge $ hhincome_broad <- as.factor(hhsurvey_merge $ hhincome_broad)
hhsurvey_merge $ smartphone_age <- as.factor(hhsurvey_merge $ smartphone_age)
hhsurvey_merge $ employment <- as.factor(hhsurvey_merge $ employment)
hhsurvey_merge $ commute_mode <- as.factor(hhsurvey_merge $ commute_mode)
hhsurvey_merge $ av_interest_6 <- as.factor(hhsurvey_merge $ av_interest_6)
hhsurvey_merge $ cityofseattle <- as.factor(hhsurvey_merge $ cityofseattle)
hhsurvey_merge $ hhid<-NULL

str(hhsurvey_merge)
a <- hhsurvey_merge %>% 
      dplyr::select(gender, age, education, license, hhincome_broad, smartphone_age, employment, commute_mode,cityofseattle)
summary(a)
str(a)

```

```{r convert into number}
hhsurvey_merge $ gender <- as.numeric(hhsurvey_merge $ gender)
hhsurvey_merge $ age <- as.numeric(hhsurvey_merge $ age)
hhsurvey_merge $ education <- as.numeric(hhsurvey_merge $ education)
hhsurvey_merge $ license <- as.numeric(hhsurvey_merge $ license)
hhsurvey_merge $ hhincome_broad <- as.numeric(hhsurvey_merge $ hhincome_broad)
hhsurvey_merge $ smartphone_age <- as.numeric(hhsurvey_merge $ smartphone_age)
hhsurvey_merge $ employment <- as.numeric(hhsurvey_merge $ employment)
hhsurvey_merge $ commute_mode <- as.numeric(hhsurvey_merge $ commute_mode)
hhsurvey_merge $ av_interest_6 <- as.numeric(hhsurvey_merge $ av_interest_6)
hhsurvey_merge $ cityofseattle <- as.numeric(hhsurvey_merge $ cityofseattle)
hhsurvey_merge $ hhid<-NULL

aa <- hhsurvey_merge %>% 
      dplyr::select(gender, age, education, license, hhincome_broad, smartphone_age, employment, commute_mode,cityofseattle)
str(aa)
cor.test(aa $ education, aa $ employment, method = 'spearman')
cor.test(aa $ education, aa $ age, method = 'spearman')

corr.test(aa $ education, aa $ employment)
vif(gender, age, education, license, hhincome_broad, smartphone_age, employment, commute_mode,cityofseattle)
```

```{r correlation plot}
ggcorrplot(cor(aa, method = 'spearman'), 
           hc.order = TRUE, 
           type = "lower",
           lab = TRUE,
           digits = 3,
           lab_size = 3.2,
           lab_col = 'black')
           #outline.color = 'black', colors = c("#6D9EC1", "white", "#E46726", tl.col = 'steelblue')
#lapply(hhsurvey_person $ gender, table)
#str(hhsurvey_merge)
#hhsurvey_merge <- merge(hhsurvey_person, hhsurvey_household)
#summary(hhsurvey_merge)
ggcorrplot(cor(aa), 
           hc.order = TRUE, 
           type = "lower",
           lab = TRUE,
           digits = 3,
           lab_size = 3.5,
           pch = 'black')
           #outline.color =
```

```{r models}

# hhsurvey_merge <- data.frame(av_interest_6, age, gender, education, employment, hhincome_detailed, license, smartphone_age, cityofseattle, commute_mode)

model_a <- train(av_interest_6~gender+age+education+hhincome_broad+license+employment+cityofseattle, 
                   data=hhsurvey_merge, method="glm", family="binomial")
summary(model_a)

model_b <- train(av_interest_6 ~ age + gender + education + employment + hhincome_broad + license + cityofseattle + smartphone_age, family = "binomial", method = 'glm', data = hhsurvey_merge)
summary(model_b)

model_c <- train(av_interest_6 ~ age + gender + education + employment + hhincome_broad + license + cityofseattle + smartphone_age + commute_mode, family = "binomial", method = 'glm', data = hhsurvey_merge)
summary(model_c)

probabilities <- predict(model_c)
predicted.classes <- ifelse(probabilities > 0.5, "1", "0")
head(predicted.classes)

mydata <- hhsurvey_merge %>%
  dplyr::select_if(is.numeric) 
predictors <- colnames(mydata)
# Bind the logit and tidying the data for plot
mydata <- mydata %>%
  mutate(logit = log(probabilities/(1-probabilities))) %>%
  gather(key = "predictors", value = "predictor.value", -logit)

ggplot(mydata, aes(logit, predictor.value))+
  geom_point(size = 0.5, alpha = 0.5) +
  geom_smooth(method = "loess") + 
  theme_bw() + 
  facet_wrap(~predictors, scales = "free_y")
```

```{r}
# likelihood ratio test
# LR-test
1 - pchisq(model_a $ null.deviance - model_a $ deviance,model_a $ df.null -model_a $ df.residual) # the result shows 0: This means that p-value is 0. Therefore, we reject the null hypothesis that the model is not better than chance at predicting the outcome.
1 - pchisq(model_b $ deviance - model_b $ deviance,length(coef(model_b)) - length(coef(model_b)))

 # R-squared
pR2(model_a)
pR2(model_b)
pR2(model_c)

# Comparison of three models
1-pchisq(model_a$deviance-fit$deviance, length(coef(fit))-length(coef(fit_x1)))4




# odds ratio
y_a <- 1/(1+exp(-(3.75809-0.51770)*mean(age)-0.86513*mean(gender)-0.59461*mean(education)+0.06437*mean(employment)-0.05304*mean(hhincome_detailed)+0.05085*mean(license)-0.28188*mean(cityofseattle))) #这里是把模型输出结果带入公式里，公式是这个：p(y=1)=1/(1+exp^(-alpha+beta_1*X1+beta_2*X2))
y_a1 <- 1-y_a
odd1 <- y_a/y_a1


```

